// Generates src/components/icons/generated.tsx from design/cadence/icons/icons.json.
// Run with `bun run icons`. Each icon's SVG markup becomes real JSX elements with
// camelCased attributes, so nothing is injected as raw HTML at runtime.
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const srcPath = resolve(root, 'design/cadence/icons/icons.json');
const outPath = resolve(root, 'src/components/icons/generated.tsx');

type IconSet = { svgAttrs: string; icons: Record<string, string> };

const ALLOWED_TAGS = new Set(['path', 'circle', 'rect', 'line', 'polyline', 'polygon', 'ellipse']);
const ALLOWED_ATTRS = new Set([
    'd', 'cx', 'cy', 'r', 'rx', 'ry', 'x', 'y', 'width', 'height', 'x1', 'y1', 'x2', 'y2', 'points',
    'fill', 'fill-opacity', 'stroke', 'stroke-linejoin', 'stroke-linecap', 'stroke-miterlimit', 'transform',
]);

export const pascalCase = (name: string): string =>
    name.split('-').map(part => part.charAt(0).toUpperCase() + part.slice(1)).join('');

const camelCase = (attr: string): string => attr.replace(/-([a-z])/g, (_, c: string) => c.toUpperCase());

function toJsx(name: string, markup: string): string[] {
    const elements: string[] = [];
    // Sticky regex: every character of the markup must belong to a self-closing primitive.
    const tagRe = /\s*<([a-z]+)((?:\s+[a-z-]+="[^"]*")*)\s*\/>\s*/y;
    const text = markup;
    let match: RegExpExecArray | null;
    while (tagRe.lastIndex < text.length && (match = tagRe.exec(text))) {
        const [, tag, attrText] = match;
        if (!ALLOWED_TAGS.has(tag)) throw new Error(`${name}: <${tag}> is not an allowed primitive`);
        const attrs: string[] = [];
        for (const [, key, value] of attrText.matchAll(/([a-z-]+)="([^"]*)"/g)) {
            if (!ALLOWED_ATTRS.has(key)) throw new Error(`${name}: attribute ${key} is not allowed`);
            attrs.push(`${camelCase(key)}="${value}"`);
        }
        elements.push(`<${tag} ${attrs.join(' ')} />`);
    }
    if (tagRe.lastIndex !== text.length || elements.length === 0) {
        throw new Error(`${name}: could not parse markup near "${text.slice(tagRe.lastIndex, tagRe.lastIndex + 40)}"`);
    }
    return elements;
}

const set = JSON.parse(readFileSync(srcPath, 'utf8')) as IconSet;
const names = Object.keys(set.icons);
const seen = new Set<string>();

const blocks = names.map(name => {
    const component = pascalCase(name);
    if (seen.has(component)) throw new Error(`duplicate component name ${component}`);
    seen.add(component);
    const children = toJsx(name, set.icons[name]);
    const body = children.length === 1
        ? children[0]
        : `<>\n    ${children.join('\n    ')}\n</>`;
    return `export const ${component} = createIcon('${name}', ${body});`;
});

const out = `// Generated by scripts/gen-icons.ts from design/cadence/icons/icons.json. Do not edit.
// Run \`bun run icons\` after changing the icon set.
import { createIcon } from './Icon';

${blocks.join('\n\n')}

/** Every Cadence icon by its kebab-case name. */
export const cadenceIcons = {
${names.map(n => `    '${n}': ${pascalCase(n)},`).join('\n')}
} as const;

export type CadenceIconName = keyof typeof cadenceIcons;
`;

mkdirSync(dirname(outPath), { recursive: true });
writeFileSync(outPath, out);
console.log(`gen-icons: wrote ${names.length} icons to ${outPath.slice(root.length + 1)}`);
