// Generated by scripts/gen-icons.ts from design/cadence/icons/icons.json. Do not edit.
// Run `bun run icons` after changing the icon set.
import { createIcon } from './Icon';

export const Today = createIcon('today', <>
    <circle cx="12" cy="12" r="4.5" />
    <path d="M12 2.5v1.8M12 19.7v1.8M2.5 12h1.8M19.7 12h1.8M5.3 5.3l1.3 1.3M17.4 17.4l1.3 1.3M5.3 18.7l1.3-1.3M17.4 6.6l1.3-1.3" />
</>);

export const Timeline = createIcon('timeline', <>
    <circle cx="5.5" cy="6" r="1.8" />
    <circle cx="5.5" cy="12" r="1.8" />
    <circle cx="5.5" cy="18" r="1.8" />
    <path d="M5.5 7.8v2.4M5.5 13.8v2.4M10.5 6h10M10.5 12h7M10.5 18h10" />
</>);

export const Log = createIcon('log', <>
    <circle cx="12" cy="12" r="9" />
    <path d="M12 8v8M8 12h8" />
</>);

export const Tests = createIcon('tests', <>
    <path d="M7.5 3h9M9 3v13.5a3 3 0 0 0 6 0V3" />
    <path d="M9 11c1 .7 2 .7 3 0s2-.7 3 0" />
    <circle cx="11" cy="14.6" r="0.9" fill="currentColor" stroke="none" />
    <circle cx="13.1" cy="17" r="0.7" fill="currentColor" stroke="none" />
</>);

export const You = createIcon('you', <>
    <circle cx="12" cy="9" r="4.5" />
    <path d="M3.5 20.5c1.7-3 4.8-5 8.5-5s6.8 2 8.5 5" />
</>);

export const Injection = createIcon('injection', <>
    <rect x="8" y="2.5" width="8" height="3.5" rx="1" />
    <path d="M9.5 6v1.2C8 7.7 7 8.8 7 10.5V19a2 2 0 0 0 2 2h6a2 2 0 0 0 2-2v-8.5c0-1.7-1-2.8-2.5-3.3V6M7 13.5h10" />
</>);

export const Tablet = createIcon('tablet', <>
    <path d="M9.2 20l10.8-10.8a3.96 3.96 0 0 0-5.6-5.6L3.6 14.4A3.96 3.96 0 0 0 9.2 20z" />
    <path d="M9 9l6 6" />
</>);

export const Patch = createIcon('patch', <>
    <rect x="3.5" y="3.5" width="17" height="17" rx="4" />
    <rect x="8.5" y="8.5" width="7" height="7" rx="1.5" />
</>);

export const Gel = createIcon('gel', <>
    <path d="M7.5 3h9l-.9 11.1a1 1 0 0 1-1 .9H9.4a1 1 0 0 1-1-.9z" />
    <path d="M7.8 6.5h8.4M10.5 15v3a1 1 0 0 0 1 1h1a1 1 0 0 0 1-1v-3" />
</>);

export const Sublingual = createIcon('sublingual', <>
    <path d="M3 11c2.8-2.5 6-3 9-1.5 3-1.5 6.2-1 9 1.5-2.2 4.4-5.3 6.8-9 6.8S5.2 15.4 3 11z" />
    <path d="M3 11h18" />
    <rect x="10" y="12.6" width="4" height="2.2" rx="1.1" />
</>);

export const Reminder = createIcon('reminder', <>
    <path d="M6 10a6 6 0 0 1 12 0c0 3.6.8 5.7 1.5 7a.6.6 0 0 1-.5.9H5a.6.6 0 0 1-.5-.9C5.2 15.7 6 13.6 6 10z" />
    <path d="M9.8 20.8c.5.8 1.3 1.2 2.2 1.2s1.7-.4 2.2-1.2" />
</>);

export const Check = createIcon('check', <polyline points="4.5,12.5 9.5,17.5 19.5,7" />);

export const InTarget = createIcon('in-target', <>
    <circle cx="12" cy="12" r="9" />
    <polyline points="8,12.3 10.8,15 16,9.5" />
</>);

export const Attention = createIcon('attention', <>
    <path d="M10.3 4.2a2 2 0 0 1 3.4 0l7.6 13.3a2 2 0 0 1-1.7 3H4.4a2 2 0 0 1-1.7-3zM12 9.5V14" />
    <circle cx="12" cy="17" r="1" fill="currentColor" stroke="none" />
</>);

export const Info = createIcon('info', <>
    <circle cx="12" cy="12" r="9" />
    <path d="M12 11v5.5" />
    <circle cx="12" cy="7.8" r="1" fill="currentColor" stroke="none" />
</>);

export const Help = createIcon('help', <>
    <circle cx="12" cy="12" r="9" />
    <path d="M9.5 9.5a2.5 2.5 0 1 1 3.6 2.3c-.7.3-1.1 1-1.1 1.7v.5" />
    <circle cx="12" cy="17" r="1" fill="currentColor" stroke="none" />
</>);

export const Close = createIcon('close', <path d="M6 6l12 12M18 6L6 18" />);

export const Clock = createIcon('clock', <>
    <circle cx="12" cy="12" r="9" />
    <path d="M12 7v5l3.5 2" />
</>);

export const Supplies = createIcon('supplies', <>
    <path d="M3.5 7.5L12 3l8.5 4.5v9L12 21l-8.5-4.5z" />
    <path d="M3.5 7.5L12 12l8.5-4.5M12 12v9M7.8 5.2l8.5 4.5" />
</>);

export const BloodDrop = createIcon('blood-drop', <>
    <path d="M12 2.8c3.4 4 6.8 7.7 6.8 11.4a6.8 6.8 0 0 1-13.6 0C5.2 10.5 8.6 6.8 12 2.8z" />
    <path d="M9.2 14.8a3 3 0 0 0 2.5 2.6" />
</>);

export const ChevronRight = createIcon('chevron-right', <polyline points="9,5.5 15.5,12 9,18.5" />);

export const ChevronDown = createIcon('chevron-down', <polyline points="5.5,9 12,15.5 18.5,9" />);

export const Back = createIcon('back', <path d="M19.5 12h-15M10.5 6l-6 6 6 6" />);

export const Minus = createIcon('minus', <path d="M4.5 12h15" />);

export const Plus = createIcon('plus', <path d="M12 4.5v15M4.5 12h15" />);

export const BackedUp = createIcon('backed-up', <>
    <path d="M7 18.5a4.5 4.5 0 0 1-.6-9 6 6 0 0 1 11.5 1.5 3.8 3.8 0 0 1-.4 7.5z" />
    <polyline points="9.5,13.8 11.4,15.7 14.8,12.3" />
</>);

export const Sync = createIcon('sync', <>
    <circle cx="12" cy="12" r="2" />
    <path d="M8 8a5.7 5.7 0 0 0 0 8M16 8a5.7 5.7 0 0 1 0 8M5.2 5.2a9.6 9.6 0 0 0 0 13.6M18.8 5.2a9.6 9.6 0 0 1 0 13.6" />
</>);

export const Lock = createIcon('lock', <>
    <rect x="5" y="10.5" width="14" height="10" rx="2" />
    <path d="M8 10.5v-3a4 4 0 0 1 8 0v3M12 15v2" />
</>);

export const TwoStep = createIcon('two-step', <>
    <rect x="2.5" y="7.5" width="19" height="9" rx="3" />
    <path d="M17.5 10v4" />
    <circle cx="7" cy="12" r="1" fill="currentColor" stroke="none" />
    <circle cx="10.3" cy="12" r="1" fill="currentColor" stroke="none" />
    <circle cx="13.6" cy="12" r="1" fill="currentColor" stroke="none" />
</>);

export const Eye = createIcon('eye', <>
    <path d="M2.5 12s3.5-6.5 9.5-6.5 9.5 6.5 9.5 6.5-3.5 6.5-9.5 6.5S2.5 12 2.5 12z" />
    <circle cx="12" cy="12" r="3" />
</>);

export const Share = createIcon('share', <path d="M8.5 9H7a1.5 1.5 0 0 0-1.5 1.5v9A1.5 1.5 0 0 0 7 21h10a1.5 1.5 0 0 0 1.5-1.5v-9A1.5 1.5 0 0 0 17 9h-1.5M12 14V3M8.5 6.5L12 3l3.5 3.5" />);

export const Copy = createIcon('copy', <>
    <rect x="8" y="8" width="12.5" height="12.5" rx="2" />
    <path d="M16 8V5.5a2 2 0 0 0-2-2H5.5a2 2 0 0 0-2 2V14a2 2 0 0 0 2 2H8" />
</>);

export const External = createIcon('external', <path d="M13.5 3.5h7v7M20.5 3.5l-9 9M18 14v4.5a2 2 0 0 1-2 2H5.5a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2H10" />);

export const Delete = createIcon('delete', <path d="M4 6.5h16M9.5 6.5v-2a1 1 0 0 1 1-1h3a1 1 0 0 1 1 1v2M6 6.5l.9 13a1.5 1.5 0 0 0 1.5 1.4h7.2a1.5 1.5 0 0 0 1.5-1.4l.9-13M10 10.5v6M14 10.5v6" />);

export const Spinner = createIcon('spinner', <path d="M21 12a9 9 0 1 1-9-9" />);

export const EyeOff = createIcon('eye-off', <path d="M9.2 5.9A9.6 9.6 0 0 1 12 5.5c6 0 9.5 6.5 9.5 6.5a17 17 0 0 1-2.4 3.3M14.1 14.3A3 3 0 0 1 9.7 10M17 17.1A9.6 9.6 0 0 1 12 18.5c-6 0-9.5-6.5-9.5-6.5A17 17 0 0 1 7 6.9M4.5 4.5l15 15" />);

export const Cloud = createIcon('cloud', <path d="M7 18.5a4.5 4.5 0 0 1-.6-9 6 6 0 0 1 11.5 1.5 3.8 3.8 0 0 1-.4 7.5z" />);

export const CloudOff = createIcon('cloud-off', <path d="M9.3 5.4A6 6 0 0 1 17.9 11a3.8 3.8 0 0 1 2.4 5.6M16.5 18.5H7a4.5 4.5 0 0 1-.6-9M4 4l16 16" />);

export const Search = createIcon('search', <>
    <circle cx="10.5" cy="10.5" r="6.5" />
    <path d="M15.2 15.2l5.3 5.3" />
</>);

export const Shield = createIcon('shield', <>
    <path d="M12 3c2.6 1.4 5 2 7.5 2.2v6.3c0 4.5-3 7.9-7.5 9.5-4.5-1.6-7.5-5-7.5-9.5V5.2C7 5 9.4 4.4 12 3z" />
    <circle cx="12" cy="10" r="2.2" />
    <path d="M8.3 16.2c.8-1.6 2.1-2.4 3.7-2.4s2.9.8 3.7 2.4" />
</>);

export const Passkey = createIcon('passkey', <>
    <circle cx="9" cy="8" r="3.5" />
    <path d="M2.5 19.5c.9-3 3.4-5 6.5-5 1.2 0 2.3.3 3.2.8" />
    <circle cx="17.5" cy="12.5" r="2.5" />
    <path d="M17.5 15v5.5M17.5 18.2h1.8" />
</>);

export const Notice = createIcon('notice', <path d="M15.5 4v16l-8-4.5H5a1 1 0 0 1-1-1v-5a1 1 0 0 1 1-1h2.5zM7.5 15.5l1 4.5M18.5 9.5c.9.7 1.5 1.5 1.5 2.5s-.6 1.8-1.5 2.5" />);

export const ChevronUp = createIcon('chevron-up', <polyline points="5.5,15 12,8.5 18.5,15" />);

export const ChevronLeft = createIcon('chevron-left', <polyline points="15,5.5 8.5,12 15,18.5" />);

export const Verified = createIcon('verified', <>
    <path d="M19.67 8.82A3.6 3.6 0 0 1 19.67 15.18A3.6 3.6 0 0 1 15.18 19.67A3.6 3.6 0 0 1 8.82 19.67A3.6 3.6 0 0 1 4.33 15.18A3.6 3.6 0 0 1 4.33 8.82A3.6 3.6 0 0 1 8.82 4.33A3.6 3.6 0 0 1 15.18 4.33A3.6 3.6 0 0 1 19.67 8.82z" />
    <polyline points="8.6,12.2 10.9,14.5 15.4,10" />
</>);

export const Select = createIcon('select', <>
    <rect x="3.5" y="3.5" width="17" height="17" rx="4" />
    <polyline points="8,12.3 10.8,15 16,9.5" />
</>);

/** Every Cadence icon by its kebab-case name. */
export const cadenceIcons = {
    'today': Today,
    'timeline': Timeline,
    'log': Log,
    'tests': Tests,
    'you': You,
    'injection': Injection,
    'tablet': Tablet,
    'patch': Patch,
    'gel': Gel,
    'sublingual': Sublingual,
    'reminder': Reminder,
    'check': Check,
    'in-target': InTarget,
    'attention': Attention,
    'info': Info,
    'help': Help,
    'close': Close,
    'clock': Clock,
    'supplies': Supplies,
    'blood-drop': BloodDrop,
    'chevron-right': ChevronRight,
    'chevron-down': ChevronDown,
    'back': Back,
    'minus': Minus,
    'plus': Plus,
    'backed-up': BackedUp,
    'sync': Sync,
    'lock': Lock,
    'two-step': TwoStep,
    'eye': Eye,
    'share': Share,
    'copy': Copy,
    'external': External,
    'delete': Delete,
    'spinner': Spinner,
    'eye-off': EyeOff,
    'cloud': Cloud,
    'cloud-off': CloudOff,
    'search': Search,
    'shield': Shield,
    'passkey': Passkey,
    'notice': Notice,
    'chevron-up': ChevronUp,
    'chevron-left': ChevronLeft,
    'verified': Verified,
    'select': Select,
} as const;

export type CadenceIconName = keyof typeof cadenceIcons;
