// Generated by scripts/gen-icons.ts from design/cadence/icons/icons.json. Do not edit.
// Run `bun run icons` after changing the icon set.
import { createIcon } from './Icon';

export const Today = createIcon('today', <>
    <path d="M12 12V5.5A6.5 6.5 0 0 1 17 16Z" fill="currentColor" fillOpacity="0.18" stroke="none" />
    <path d="M13.25 3.09A9 9 0 0 1 18.19 5.46M19.75 7.42A9 9 0 0 1 20.97 12.76M20.41 15.2A9 9 0 0 1 17 19.49M14.74 20.57A9 9 0 0 1 9.26 20.57M7 19.49A9 9 0 0 1 3.59 15.2M3.03 12.76A9 9 0 0 1 4.25 7.42M5.81 5.46A9 9 0 0 1 10.75 3.09" />
    <path d="M12 12L17 16" />
</>);

export const Timeline = createIcon('timeline', <>
    <path d="M3.5 20.5C7.5 20.5 6.5 7.5 10.5 7.5C14.5 7.5 14.5 20.5 20.5 20.5Z" fill="currentColor" fillOpacity="0.18" stroke="none" />
    <path d="M3.5 4.5V20.5H20.5M3.5 20.5C7.5 20.5 6.5 7.5 10.5 7.5C14.5 7.5 14.5 20.5 20.5 20.5" />
</>);

export const Log = createIcon('log', <path d="M12 5.5V18.5M5.5 12H18.5" />);

export const Tests = createIcon('tests', <>
    <path d="M8.5 12.5V16.5A3.5 3.5 0 0 0 15.5 16.5V12.5Z" fill="currentColor" fillOpacity="0.18" stroke="none" />
    <path d="M7 4H17M8.5 4V16.5A3.5 3.5 0 0 0 15.5 16.5V4M8.5 12.5H15.5" />
</>);

export const You = createIcon('you', <>
    <path d="M4.5 20.5A7.5 7.5 0 0 1 19.5 20.5Z" fill="currentColor" fillOpacity="0.18" stroke="none" />
    <circle cx="12" cy="7.5" r="3.5" />
    <path d="M4.5 20.5A7.5 7.5 0 0 1 19.5 20.5Z" />
</>);

export const Injection = createIcon('injection', <>
    <path d="M8.75 10.5H15.25V16.5A1.5 1.5 0 0 1 13.75 18H10.25A1.5 1.5 0 0 1 8.75 16.5Z" transform="rotate(45 12 12)" fill="currentColor" fillOpacity="0.18" stroke="none" />
    <rect x="8.75" y="6.5" width="6.5" height="11.5" rx="1.5" transform="rotate(45 12 12)" />
    <path d="M8.75 10.5H15.25M12 2V10.5M9.5 2H14.5M7 6.5H17M12 18V22.5" transform="rotate(45 12 12)" />
</>);

export const Tablet = createIcon('tablet', <>
    <path d="M12 5.5A8.5 5 0 0 0 12 15.5Z" fill="currentColor" fillOpacity="0.18" stroke="none" />
    <ellipse cx="12" cy="10.5" rx="8.5" ry="5" />
    <path d="M3.5 10.5V13.5A8.5 5 0 0 0 20.5 13.5V10.5M12 5.5V15.5" />
</>);

export const Patch = createIcon('patch', <>
    <path d="M3.5 7A3.5 3.5 0 0 1 7 3.5H17A3.5 3.5 0 0 1 20.5 7V13L13 20.5H7A3.5 3.5 0 0 1 3.5 17Z" fill="currentColor" fillOpacity="0.18" stroke="none" />
    <path d="M20.5 13V7A3.5 3.5 0 0 0 17 3.5H7A3.5 3.5 0 0 0 3.5 7V17A3.5 3.5 0 0 0 7 20.5H13" />
    <path d="M20.5 13L13 20.5C13 17 14 15 15 14C16 13 17.5 13 20.5 13Z" />
</>);

export const Gel = createIcon('gel', <>
    <path d="M7 15V18.5A2.5 2.5 0 0 0 9.5 21H14.5A2.5 2.5 0 0 0 17 18.5V15Z" fill="currentColor" fillOpacity="0.18" stroke="none" />
    <rect x="7" y="9.5" width="10" height="11.5" rx="2.5" />
    <path d="M10 9.5V7H14V9.5M12 7V4M15 4H8.5L6.5 5.5M7 15H17" />
</>);

export const Sublingual = createIcon('sublingual', <>
    <ellipse cx="12.5" cy="18.5" rx="3.5" ry="2" fill="currentColor" fillOpacity="0.18" stroke="none" />
    <path d="M3.5 8C7.5 8 9 4.5 13 4.5H15C18 4.5 20.5 6.5 20.5 9C20.5 11.5 18.5 13.5 15 13.5H3.5" />
    <ellipse cx="12.5" cy="18.5" rx="3.5" ry="2" />
</>);

export const Reminder = createIcon('reminder', <>
    <path d="M7 13.5H17C17 15 17.5 15.5 19 16.5H5C6.5 15.5 7 15 7 13.5Z" fill="currentColor" fillOpacity="0.18" stroke="none" />
    <path d="M5 16.5C6.5 15 7 13 7 10.5A5 5 0 0 1 17 10.5C17 13 17.5 15 19 16.5ZM7 13.5H17M10 19A2 2 0 0 0 14 19M12 3.5V5.5" />
</>);

export const Assistant = createIcon('assistant', <>
    <path d="M13.5 6.5V17.5H11A5.5 5.5 0 0 1 11 6.5Z" fill="currentColor" fillOpacity="0.18" stroke="none" />
    <path d="M13.5 6.5V17.5H11A5.5 5.5 0 0 1 11 6.5ZM13.5 9.5H17M13.5 14.5H17M20.5 5V19M5.5 12H5A1.5 1.5 0 0 0 3.5 13.5V20.5" />
</>);

export const Check = createIcon('check', <path strokeLinejoin="miter" strokeMiterlimit="10" d="M4.5 12.5L9.5 17.5L19.5 6" />);

export const InTarget = createIcon('in-target', <>
    <circle cx="12" cy="12" r="9" fill="currentColor" fillOpacity="0.18" stroke="none" />
    <circle cx="12" cy="12" r="9" />
    <path strokeLinejoin="miter" strokeMiterlimit="10" d="M8 12.5L11 15.5L16.5 8.5" />
</>);

export const Up = createIcon('up', <path d="M12 19V5.5M7 9L12 5L17 9" />);

export const Down = createIcon('down', <path d="M12 5V18.5M7 15L12 19L17 15" />);

export const Attention = createIcon('attention', <>
    <path d="M14.19 5.46L20.45 16.79A2.5 2.5 0 0 1 18.26 20.5L5.74 20.5A2.5 2.5 0 0 1 3.55 16.79L9.81 5.46A2.5 2.5 0 0 1 14.19 5.46Z" fill="currentColor" fillOpacity="0.18" stroke="none" />
    <path d="M14.19 5.46L20.45 16.79A2.5 2.5 0 0 1 18.26 20.5L5.74 20.5A2.5 2.5 0 0 1 3.55 16.79L9.81 5.46A2.5 2.5 0 0 1 14.19 5.46Z" />
    <path d="M12 9V15" />
</>);

export const Info = createIcon('info', <>
    <path d="M12 7.5A10 10 0 0 0 3.5 5.5V18A10 10 0 0 1 12 20Z" fill="currentColor" fillOpacity="0.18" stroke="none" />
    <path d="M12 7.5A10 10 0 0 0 3.5 5.5V18A10 10 0 0 1 12 20A10 10 0 0 1 20.5 18V5.5A10 10 0 0 0 12 7.5V20" />
</>);

export const Close = createIcon('close', <path d="M6.5 6.5L17.5 17.5M17.5 6.5L6.5 17.5" />);

export const Clock = createIcon('clock', <>
    <circle cx="12" cy="12" r="9" />
    <path d="M12 7V12H15.5" />
</>);

export const Calendar = createIcon('calendar', <>
    <path d="M3.5 10H20.5V15H12V20.5H6A2.5 2.5 0 0 1 3.5 18Z" fill="currentColor" fillOpacity="0.18" stroke="none" />
    <rect x="3.5" y="5" width="17" height="15.5" rx="2.5" />
    <path d="M3.5 10H20.5M3.5 15H20.5M12 15V20.5M8.5 3V6.5M15.5 3V6.5" />
</>);

export const Snooze = createIcon('snooze', <>
    <path d="M7.42 15H16.58A5 5 0 0 1 17 17V20.5H7V17A5 5 0 0 1 7.42 15Z" fill="currentColor" fillOpacity="0.18" stroke="none" />
    <path d="M5.5 3.5H18.5M5.5 20.5H18.5M7 3.5V7A5 5 0 0 0 17 7V3.5M7 20.5V17A5 5 0 0 1 17 17V20.5M7.42 15H16.58" />
</>);

export const Skip = createIcon('skip', <>
    <path d="M3.5 12.5A4.5 4.5 0 0 1 12.5 12.5H20.5M17.5 9L20.5 12.5L17.5 16" />
    <path d="M8 10V15" />
</>);

export const Repeat = createIcon('repeat', <path d="M15.75 6A7.5 7.5 0 1 1 8.25 6M7.5 10L8.25 6L4.5 4.5" />);

export const Supplies = createIcon('supplies', <>
    <path d="M7.5 15.5H16.5V18.5A2.5 2.5 0 0 1 14 21H10A2.5 2.5 0 0 1 7.5 18.5Z" fill="currentColor" fillOpacity="0.18" stroke="none" />
    <rect x="8.5" y="3" width="7" height="3.5" rx="1.5" />
    <path d="M10 6.5V8.5H9A1.5 1.5 0 0 0 7.5 10V18.5A2.5 2.5 0 0 0 10 21H14A2.5 2.5 0 0 0 16.5 18.5V10A1.5 1.5 0 0 0 15 8.5H14V6.5M7.5 15.5H16.5" />
</>);

export const Reorder = createIcon('reorder', <>
    <path d="M4.5 10.5H19.5V18A2.5 2.5 0 0 1 17 20.5H7A2.5 2.5 0 0 1 4.5 18Z" fill="currentColor" fillOpacity="0.18" stroke="none" />
    <path d="M4.5 10.5V18A2.5 2.5 0 0 0 7 20.5H17A2.5 2.5 0 0 0 19.5 18V10.5ZM4.5 10.5L3 6.5H10.5L12 10.5L13.5 6.5H21L19.5 10.5" />
</>);

export const Site = createIcon('site', <>
    <path d="M12 13A7.5 7.5 0 0 0 4.5 20.5H12Z" fill="currentColor" fillOpacity="0.18" stroke="none" />
    <circle cx="12" cy="7.5" r="3.5" />
    <path d="M4.5 20.5A7.5 7.5 0 0 1 19.5 20.5ZM12 13V20.5" />
</>);

export const BloodDrop = createIcon('blood-drop', <>
    <path d="M6.52 14.5H17.48A5.5 5.5 0 1 1 6.52 14.5Z" fill="currentColor" fillOpacity="0.18" stroke="none" />
    <path d="M12 3.5L16.83 12.37A5.5 5.5 0 1 1 7.17 12.37Z" />
    <path d="M6.52 14.5H17.48" />
</>);

export const ChevronRight = createIcon('chevron-right', <path d="M10 6.5L14.5 12L10 17.5" />);

export const ChevronDown = createIcon('chevron-down', <path d="M6.5 10L12 14.5L17.5 10" />);

export const Back = createIcon('back', <path d="M19 12H5.5M9 7L5 12L9 17" />);

export const Minus = createIcon('minus', <path d="M6.5 12H17.5" />);

export const Plus = createIcon('plus', <path d="M12 6.5V17.5M6.5 12H17.5" />);

export const More = createIcon('more', <path d="M3.5 12H6.5M10.5 12H13.5M17.5 12H20.5" />);

export const BackedUp = createIcon('backed-up', <>
    <path d="M7 19A4 4 0 0 1 7 11A5.5 5.5 0 1 1 17.77 12.09A3.5 3.5 0 0 1 17 19Z" fill="currentColor" fillOpacity="0.18" stroke="none" />
    <path d="M7 19A4 4 0 0 1 7 11A5.5 5.5 0 1 1 17.77 12.09A3.5 3.5 0 0 1 17 19Z" />
    <path strokeLinejoin="miter" strokeMiterlimit="10" d="M8.5 13L11 15.5L15.5 10" />
</>);

export const Sync = createIcon('sync', <>
    <path d="M4 12A8 8 0 0 1 18.5 7.5M20 12A8 8 0 0 1 5.5 16.5" />
    <path d="M19 4L18.5 7.5L15 7M5 20L5.5 16.5L9 17" />
</>);

export const Lock = createIcon('lock', <>
    <rect x="5" y="10.5" width="14" height="10" rx="2.5" fill="currentColor" fillOpacity="0.18" stroke="none" />
    <rect x="5" y="10.5" width="14" height="10" rx="2.5" />
    <path d="M8.5 10.5V7.5A3.5 3.5 0 0 1 15.5 7.5V10.5M12 14V17" />
</>);

export const TwoStep = createIcon('two-step', <>
    <path d="M6.5 4H17.5A1.5 1.5 0 0 1 19 5.5V11A9.5 9.5 0 0 1 12 20.5A9.5 9.5 0 0 1 5 11V5.5A1.5 1.5 0 0 1 6.5 4Z" fill="currentColor" fillOpacity="0.18" stroke="none" />
    <path d="M6.5 4H17.5A1.5 1.5 0 0 1 19 5.5V11A9.5 9.5 0 0 1 12 20.5A9.5 9.5 0 0 1 5 11V5.5A1.5 1.5 0 0 1 6.5 4Z" />
    <path strokeLinejoin="miter" strokeMiterlimit="10" d="M8.5 11.5L11 14L15.5 8.5" />
</>);

export const Key = createIcon('key', <>
    <circle cx="8" cy="12" r="5" fill="currentColor" fillOpacity="0.18" stroke="none" />
    <circle cx="8" cy="12" r="5" />
    <path d="M13 12H20.5V16M17 12V15" />
</>);

export const SignIn = createIcon('sign-in', <>
    <path d="M10 6A2.5 2.5 0 0 1 12.5 3.5H18A2.5 2.5 0 0 1 20.5 6V18A2.5 2.5 0 0 1 18 20.5H12.5A2.5 2.5 0 0 1 10 18Z" fill="currentColor" fillOpacity="0.18" stroke="none" />
    <path d="M10 9.5V6A2.5 2.5 0 0 1 12.5 3.5H18A2.5 2.5 0 0 1 20.5 6V18A2.5 2.5 0 0 1 18 20.5H12.5A2.5 2.5 0 0 1 10 18V14.5" />
    <path d="M3.5 12H16.5M13 8.5L16.5 12L13 15.5" />
</>);

export const SignOut = createIcon('sign-out', <>
    <path d="M3.5 6A2.5 2.5 0 0 1 6 3.5H11.5A2.5 2.5 0 0 1 14 6V18A2.5 2.5 0 0 1 11.5 20.5H6A2.5 2.5 0 0 1 3.5 18Z" fill="currentColor" fillOpacity="0.18" stroke="none" />
    <path d="M14 9.5V6A2.5 2.5 0 0 0 11.5 3.5H6A2.5 2.5 0 0 0 3.5 6V18A2.5 2.5 0 0 0 6 20.5H11.5A2.5 2.5 0 0 0 14 18V14.5" />
    <path d="M7.5 12H20.5M17 8.5L20.5 12L17 15.5" />
</>);

export const Eye = createIcon('eye', <>
    <circle cx="12" cy="12" r="3.5" fill="currentColor" fillOpacity="0.18" stroke="none" />
    <path d="M3 12A10 10 0 0 1 21 12A10 10 0 0 1 3 12Z" />
    <circle cx="12" cy="12" r="3.5" />
</>);

export const Language = createIcon('language', <>
    <path d="M12 3A5 9 0 0 0 12 21A9 9 0 0 0 12 3Z" fill="currentColor" fillOpacity="0.18" stroke="none" />
    <circle cx="12" cy="12" r="9" />
    <path d="M12 3A5 9 0 0 0 12 21M3 12H21" />
</>);

export const Appearance = createIcon('appearance', <>
    <path d="M12 3.5A8.5 8.5 0 0 0 12 20.5Z" fill="currentColor" fillOpacity="0.18" stroke="none" />
    <circle cx="12" cy="12" r="8.5" />
    <path d="M12 3.5V20.5" />
</>);

export const Weight = createIcon('weight', <>
    <path d="M12 11H6.5A5.5 5.5 0 0 1 15.89 7.11Z" fill="currentColor" fillOpacity="0.18" stroke="none" />
    <rect x="3.5" y="3.5" width="17" height="17" rx="3.5" />
    <path d="M6.5 11A5.5 5.5 0 0 1 17.5 11ZM12 11L14.5 8.5" />
</>);

export const Summary = createIcon('summary', <>
    <path d="M5 8.5V5.5A2.5 2.5 0 0 1 7.5 3H16.5A2.5 2.5 0 0 1 19 5.5V8.5Z" fill="currentColor" fillOpacity="0.18" stroke="none" />
    <rect x="5" y="3" width="14" height="18" rx="2.5" />
    <path d="M5 8.5H19M8.5 12.5H15.5M8.5 16.5H13" />
</>);

export const Export = createIcon('export', <>
    <rect x="3.5" y="16" width="17" height="4.5" rx="1.5" fill="currentColor" fillOpacity="0.18" stroke="none" />
    <rect x="3.5" y="16" width="17" height="4.5" rx="1.5" />
    <path d="M12 3.5V12.5M8.5 9L12 12.5L15.5 9" />
</>);

export const Import = createIcon('import', <>
    <rect x="3.5" y="16" width="17" height="4.5" rx="1.5" fill="currentColor" fillOpacity="0.18" stroke="none" />
    <rect x="3.5" y="16" width="17" height="4.5" rx="1.5" />
    <path d="M12 12.5V3.5M8.5 7L12 3.5L15.5 7" />
</>);

export const Share = createIcon('share', <>
    <circle cx="6.5" cy="12" r="3.5" fill="currentColor" fillOpacity="0.18" stroke="none" />
    <circle cx="6.5" cy="12" r="3.5" />
    <circle cx="17.5" cy="5.5" r="2.5" />
    <circle cx="17.5" cy="18.5" r="2.5" />
    <path d="M10 12A7.5 4 0 0 0 17.5 8M10 12A7.5 4 0 0 1 17.5 16" />
</>);

export const Link = createIcon('link', <path d="M7.5 12.5L4.5 15.5A2.83 2.83 0 0 0 8.5 19.5L11.5 16.5M16.5 11.5L19.5 8.5A2.83 2.83 0 0 0 15.5 4.5L12.5 7.5M8.5 15.5L15.5 8.5" />);

export const Copy = createIcon('copy', <>
    <path d="M8.5 6.5V6A2.5 2.5 0 0 1 11 3.5H18A2.5 2.5 0 0 1 20.5 6V15A2.5 2.5 0 0 1 18 17.5H15.5V9A2.5 2.5 0 0 0 13 6.5Z" fill="currentColor" fillOpacity="0.18" stroke="none" />
    <rect x="3.5" y="6.5" width="12" height="14" rx="2.5" />
    <path d="M8.5 6.5V6A2.5 2.5 0 0 1 11 3.5H18A2.5 2.5 0 0 1 20.5 6V15A2.5 2.5 0 0 1 18 17.5H15.5" />
    <path d="M7 12.5H12M7 16.5H10.5" />
</>);

export const External = createIcon('external', <>
    <path d="M3.5 7A3.5 3.5 0 0 1 7 3.5H20.5V17A3.5 3.5 0 0 1 17 20.5H7A3.5 3.5 0 0 1 3.5 17Z" fill="currentColor" fillOpacity="0.18" stroke="none" />
    <path d="M11.5 3.5H7A3.5 3.5 0 0 0 3.5 7V17A3.5 3.5 0 0 0 7 20.5H17A3.5 3.5 0 0 0 20.5 17V12.5" />
    <path d="M11 13L20.5 3.5M16 3.5H20.5V8" />
</>);

export const Edit = createIcon('edit', <>
    <path d="M4 20L6.5 14.5L9.5 17.5Z" fill="currentColor" fillOpacity="0.18" stroke="none" />
    <path d="M4 20L6.5 14.5L17 4L20 7L9.5 17.5ZM6.5 14.5L9.5 17.5M14.5 6.5L17.5 9.5" />
</>);

export const Delete = createIcon('delete', <>
    <path d="M6 6.5V18A2.5 2.5 0 0 0 8.5 20.5H15.5A2.5 2.5 0 0 0 18 18V6.5Z" fill="currentColor" fillOpacity="0.18" stroke="none" />
    <path d="M3.5 6.5H20.5M9.5 6.5A2.5 2.5 0 0 1 14.5 6.5M6 6.5V18A2.5 2.5 0 0 0 8.5 20.5H15.5A2.5 2.5 0 0 0 18 18V6.5" />
</>);

export const Server = createIcon('server', <>
    <path d="M4 12V17.5A2.5 2.5 0 0 0 6.5 20H17.5A2.5 2.5 0 0 0 20 17.5V12Z" fill="currentColor" fillOpacity="0.18" stroke="none" />
    <rect x="4" y="4" width="16" height="16" rx="2.5" />
    <path d="M4 12H20M7.5 8H11M7.5 16H11" />
</>);

export const Terminal = createIcon('terminal', <>
    <rect x="3" y="4" width="18" height="16" rx="2.5" fill="currentColor" fillOpacity="0.18" stroke="none" />
    <rect x="3" y="4" width="18" height="16" rx="2.5" />
    <path d="M7 9L10 12L7 15M12.5 15H17" />
</>);

export const Laptop = createIcon('laptop', <>
    <rect x="5" y="4.5" width="14" height="11" rx="2.5" fill="currentColor" fillOpacity="0.18" stroke="none" />
    <rect x="5" y="4.5" width="14" height="11" rx="2.5" />
    <path d="M3 19H21" />
</>);

export const Phone = createIcon('phone', <>
    <rect x="6.5" y="3" width="11" height="18" rx="2.5" fill="currentColor" fillOpacity="0.18" stroke="none" />
    <rect x="6.5" y="3" width="11" height="18" rx="2.5" />
    <path d="M10 17.5H14" />
</>);

export const ActivityLog = createIcon('activity-log', <>
    <path d="M12 12.5V7.5A5 5 0 0 0 7.76 15.15Z" fill="currentColor" fillOpacity="0.18" stroke="none" />
    <path d="M14.5 5A7.91 7.91 0 1 1 9.5 5" />
    <path d="M16 7.5L14.5 5L17 3.5" />
    <path d="M12 12.5V7.5M12 12.5L8 15" />
</>);

export const Permissions = createIcon('permissions', <>
    <path d="M7 3.5H17A3.5 3.5 0 0 0 17 10.5H7A3.5 3.5 0 0 1 7 3.5Z" fill="currentColor" fillOpacity="0.18" stroke="none" />
    <rect x="3.5" y="3.5" width="17" height="7" rx="3.5" />
    <rect x="3.5" y="13.5" width="17" height="7" rx="3.5" />
    <path d="M17 3.5A3.5 3.5 0 0 0 17 10.5M7 13.5A3.5 3.5 0 0 1 7 20.5" />
</>);

export const Moon = createIcon('moon', <>
    <path d="M15.12 3.91A8.5 8.5 0 1 0 19 17.48A7.5 7.5 0 0 1 15.12 3.91Z" fill="currentColor" fillOpacity="0.18" stroke="none" />
    <path d="M15.12 3.91A8.5 8.5 0 1 0 19 17.48A7.5 7.5 0 0 1 15.12 3.91Z" />
</>);

export const Spinner = createIcon('spinner', <path d="M12 3.5A8.5 8.5 0 1 1 3.5 12" />);

export const EyeOff = createIcon('eye-off', <path d="M3 9A10 10 0 0 0 21 9M6.86 13.22L5.5 15.5M12 14.64L12 17.5M17.14 13.22L18.5 15.5" />);

export const Cloud = createIcon('cloud', <>
    <path d="M7 19A4 4 0 0 1 7 11A5.5 5.5 0 1 1 17.77 12.09A3.5 3.5 0 0 1 17 19Z" fill="currentColor" fillOpacity="0.18" stroke="none" />
    <path d="M7 19A4 4 0 0 1 7 11A5.5 5.5 0 1 1 17.77 12.09A3.5 3.5 0 0 1 17 19Z" />
</>);

export const CloudOff = createIcon('cloud-off', <>
    <path d="M7 19A4 4 0 0 1 7 11A5.5 5.5 0 0 1 6.99 10.25M9.32 6.07A5.5 5.5 0 0 1 17.77 12.09A3.5 3.5 0 0 1 20.18 16.93M15.5 19H7" />
    <path d="M4 4L20 20" />
</>);

export const CloudUpload = createIcon('cloud-upload', <>
    <path d="M7 19A4 4 0 0 1 7 11A5.5 5.5 0 1 1 17.77 12.09A3.5 3.5 0 0 1 17 19Z" fill="currentColor" fillOpacity="0.18" stroke="none" />
    <path d="M7 19A4 4 0 0 1 7 11A5.5 5.5 0 1 1 17.77 12.09A3.5 3.5 0 0 1 17 19Z" />
    <path d="M12 16.5V10M9 12.5L12 9.5L15 12.5" />
</>);

export const CloudDownload = createIcon('cloud-download', <>
    <path d="M7 19A4 4 0 0 1 7 11A5.5 5.5 0 1 1 17.77 12.09A3.5 3.5 0 0 1 17 19Z" fill="currentColor" fillOpacity="0.18" stroke="none" />
    <path d="M7 19A4 4 0 0 1 7 11A5.5 5.5 0 1 1 17.77 12.09A3.5 3.5 0 0 1 17 19Z" />
    <path d="M12 9.5V16M9 13.5L12 16.5L15 13.5" />
</>);

export const Search = createIcon('search', <>
    <circle cx="10.5" cy="10.5" r="6.5" fill="currentColor" fillOpacity="0.18" stroke="none" />
    <circle cx="10.5" cy="10.5" r="6.5" />
    <rect x="9" y="17" width="3" height="6.5" rx="1.5" transform="rotate(-45 10.5 10.5)" />
</>);

export const Settings = createIcon('settings', <>
    <circle cx="12" cy="12" r="3" fill="currentColor" fillOpacity="0.18" stroke="none" />
    <path d="M10.21 5.75L10.44 3.14A9 9 0 0 1 13.56 3.14L13.79 5.75A6.5 6.5 0 0 1 16.52 7.32L18.89 6.21A9 9 0 0 1 20.46 8.92L18.31 10.43A6.5 6.5 0 0 1 18.31 13.57L20.46 15.08A9 9 0 0 1 18.89 17.79L16.52 16.68A6.5 6.5 0 0 1 13.79 18.25L13.56 20.86A9 9 0 0 1 10.44 20.86L10.21 18.25A6.5 6.5 0 0 1 7.48 16.68L5.11 17.79A9 9 0 0 1 3.54 15.08L5.69 13.57A6.5 6.5 0 0 1 5.69 10.43L3.54 8.92A9 9 0 0 1 5.11 6.21L7.48 7.32A6.5 6.5 0 0 1 10.21 5.75Z" />
    <circle cx="12" cy="12" r="3" />
</>);

export const Sliders = createIcon('sliders', <>
    <path d="M3.5 8H7M11 8H20.5M3.5 16H13M17 16H20.5" />
    <rect x="7" y="5" width="4" height="6" rx="1.5" />
    <rect x="13" y="13" width="4" height="6" rx="1.5" />
</>);

export const Users = createIcon('users', <>
    <path d="M3 20.5A6 6 0 0 1 15 20.5Z" fill="currentColor" fillOpacity="0.18" stroke="none" />
    <circle cx="9" cy="9" r="3" />
    <path d="M3 20.5A6 6 0 0 1 15 20.5Z" />
    <path d="M13.05 5.27A3 3 0 1 1 14.45 9.81M15.6 14.53A6 6 0 0 1 21 20.5" />
</>);

export const Shield = createIcon('shield', <>
    <path d="M12 4H6.5A1.5 1.5 0 0 0 5 5.5V11A9.5 9.5 0 0 0 12 20.5Z" fill="currentColor" fillOpacity="0.18" stroke="none" />
    <path d="M6.5 4H17.5A1.5 1.5 0 0 1 19 5.5V11A9.5 9.5 0 0 1 12 20.5A9.5 9.5 0 0 1 5 11V5.5A1.5 1.5 0 0 1 6.5 4Z" />
    <path d="M12 4V20.5" />
</>);

export const ShieldOff = createIcon('shield-off', <>
    <path d="M7.5 4H17.5A1.5 1.5 0 0 1 19 5.5V11A9.5 9.5 0 0 1 18.26 15.01M15.47 18.73A9.5 9.5 0 0 1 12 20.5A9.5 9.5 0 0 1 5 11V8.5" />
    <path d="M3.5 3.5L20.5 20.5" />
</>);

export const Passkey = createIcon('passkey', <path d="M3.5 17V12A8.5 8.5 0 0 1 20.5 12V13.5M7 20.5V12A5 5 0 0 1 17 12V19M10.5 16V12A1.5 1.5 0 0 1 13.5 12V20.5" />);

export const ImageAdd = createIcon('image-add', <>
    <path d="M3.5 14.5L7 11L11 15L16.5 13L20.5 16.5V17A2.5 2.5 0 0 1 18 19.5H6A2.5 2.5 0 0 1 3.5 17Z" fill="currentColor" fillOpacity="0.18" stroke="none" />
    <rect x="3.5" y="4.5" width="17" height="15" rx="2.5" />
    <path d="M3.5 14.5L7 11L11 15L16.5 13L20.5 16.5" />
    <path d="M16 7V11M14 9H18" />
</>);

export const ImageOff = createIcon('image-off', <>
    <path d="M8 4.5H18A2.5 2.5 0 0 1 20.5 7V17M16 19.5H6A2.5 2.5 0 0 1 3.5 17V7M3.5 14.5L7 11L11 15M16.5 13L20.5 16.5" />
    <path d="M3.5 3.5L20.5 20.5" />
</>);

export const Template = createIcon('template', <>
    <path d="M7.5 3.5V20.5L12 16.5L16.5 20.5V3.5Z" fill="currentColor" fillOpacity="0.18" stroke="none" />
    <path d="M7.5 3.5V20.5L12 16.5L16.5 20.5V3.5M4.5 3.5H19.5" />
</>);

export const TemplateAdd = createIcon('template-add', <>
    <path d="M4.5 3.5V20.5L8.5 17L12.5 20.5V3.5Z" fill="currentColor" fillOpacity="0.18" stroke="none" />
    <path d="M4.5 3.5V20.5L8.5 17L12.5 20.5V3.5M3 3.5H14" />
    <path d="M17.5 8V14M14.5 11H20.5" />
</>);

export const Reset = createIcon('reset', <path d="M5.5 9.25A7.5 7.5 0 1 0 12 5.5M14.5 3L12 5.5L14.5 8" />);

export const Save = createIcon('save', <>
    <path d="M7 20.5V14.5A1.5 1.5 0 0 1 8.5 13H15.5A1.5 1.5 0 0 1 17 14.5V20.5Z" fill="currentColor" fillOpacity="0.18" stroke="none" />
    <path d="M3.5 6A2.5 2.5 0 0 1 6 3.5H16.5L20.5 7.5V18A2.5 2.5 0 0 1 18 20.5H6A2.5 2.5 0 0 1 3.5 18Z" />
    <path d="M7.5 3.5V6.5A1.5 1.5 0 0 0 9 8H13.5A1.5 1.5 0 0 0 15 6.5V3.5M7 20.5V14.5A1.5 1.5 0 0 1 8.5 13H15.5A1.5 1.5 0 0 1 17 14.5V20.5" />
</>);

export const Notice = createIcon('notice', <>
    <path d="M8 9L18 4.5V19.5L8 15Z" fill="currentColor" fillOpacity="0.18" stroke="none" />
    <rect x="3.5" y="9" width="4.5" height="6" rx="1.5" />
    <path d="M8 9L18 4.5V19.5L8 15" />
    <path d="M20.5 9.5V14.5M5.5 15L6.5 19.5H9L9.5 16" />
</>);

export const Database = createIcon('database', <>
    <path d="M5 13.5A7 2.5 0 0 0 19 13.5V18A7 2.5 0 0 1 5 18Z" fill="currentColor" fillOpacity="0.18" stroke="none" />
    <ellipse cx="12" cy="6" rx="7" ry="2.5" />
    <path d="M5 6V18A7 2.5 0 0 0 19 18V6M5 13.5A7 2.5 0 0 0 19 13.5" />
</>);

export const HardDrive = createIcon('hard-drive', <>
    <rect x="3" y="13" width="18" height="6" rx="1.5" fill="currentColor" fillOpacity="0.18" stroke="none" />
    <rect x="3" y="13" width="18" height="6" rx="1.5" />
    <path d="M5 13V7.5A2.5 2.5 0 0 1 7.5 5H16.5A2.5 2.5 0 0 1 19 7.5V13M14.5 16H17.5" />
</>);

export const Merge = createIcon('merge', <path d="M3.5 5.5H5.5A6.5 6.5 0 0 1 12 12A6.5 6.5 0 0 1 5.5 18.5H3.5M12 12H20.5M16.5 7.5L20.5 12L16.5 16.5" />);

export const Desktop = createIcon('desktop', <>
    <rect x="3.5" y="3.5" width="17" height="12.5" rx="2.5" fill="currentColor" fillOpacity="0.18" stroke="none" />
    <rect x="3.5" y="3.5" width="17" height="12.5" rx="2.5" />
    <path d="M10.5 16L9.5 20.5H14.5L13.5 16" />
</>);

export const Devices = createIcon('devices', <>
    <rect x="14" y="8.5" width="7" height="12" rx="1.5" fill="currentColor" fillOpacity="0.18" stroke="none" />
    <path d="M12.5 13.5H6.5A2.5 2.5 0 0 1 4 11V6A2.5 2.5 0 0 1 6.5 3.5H14A2.5 2.5 0 0 1 16.5 6V7" />
    <path d="M3 17H12.5" />
    <rect x="14" y="8.5" width="7" height="12" rx="1.5" />
</>);

export const ChevronUp = createIcon('chevron-up', <path d="M6.5 14L12 9.5L17.5 14" />);

export const ChevronLeft = createIcon('chevron-left', <path d="M14 6.5L9.5 12L14 17.5" />);

export const Off = createIcon('off', <>
    <path d="M16.16 19.41A8.5 8.5 0 0 1 4.59 7.84M7.84 4.59A8.5 8.5 0 0 1 19.41 16.16" />
    <path d="M3.5 3.5L20.5 20.5" />
</>);

export const Verified = createIcon('verified', <>
    <path d="M12 3L14.87 5.07L18.36 5.64L18.93 9.13L21 12L18.93 14.87L18.36 18.36L14.87 18.93L12 21L9.13 18.93L5.64 18.36L5.07 14.87L3 12L5.07 9.13L5.64 5.64L9.13 5.07Z" fill="currentColor" fillOpacity="0.18" stroke="none" />
    <path d="M12 3L14.87 5.07L18.36 5.64L18.93 9.13L21 12L18.93 14.87L18.36 18.36L14.87 18.93L12 21L9.13 18.93L5.64 18.36L5.07 14.87L3 12L5.07 9.13L5.64 5.64L9.13 5.07Z" />
    <path strokeLinejoin="miter" strokeMiterlimit="10" d="M8.5 12L11 14.5L15.5 9" />
</>);

export const Select = createIcon('select', <>
    <path d="M3.5 6H20.5M3.5 12H13M3.5 18H9" />
    <path strokeLinejoin="miter" strokeMiterlimit="10" d="M12.5 16.5L15.5 19.5L20.5 13" />
</>);

export const Forward = createIcon('forward', <path d="M4.5 5V19M9 6.5L13.5 12L9 17.5M14.5 6.5L19 12L14.5 17.5" />);

export const Rewind = createIcon('rewind', <path d="M19.5 5V19M15 6.5L10.5 12L15 17.5M9.5 6.5L5 12L9.5 17.5" />);

export const Gauge = createIcon('gauge', <>
    <path d="M12 16.5H5.9A6.1 6.1 0 0 1 15.5 11.5Z" fill="currentColor" fillOpacity="0.18" stroke="none" />
    <path d="M3 16.5A9 9 0 0 1 21 16.5Z" />
    <path d="M12 16.5L15.5 11.5" />
</>);

export const Radar = createIcon('radar', <>
    <path d="M12 12V3.5A8.5 8.5 0 0 1 18.01 5.99Z" fill="currentColor" fillOpacity="0.18" stroke="none" />
    <circle cx="12" cy="12" r="8.5" />
    <circle cx="12" cy="12" r="4.5" />
    <path d="M12 12L18.01 5.99" />
</>);

export const Wind = createIcon('wind', <>
    <path d="M5 5L10 5.5V11.5L5 12Z" fill="currentColor" fillOpacity="0.18" stroke="none" />
    <path d="M5 3.5V20.5" />
    <path d="M5 5L20 6.5V10.5L5 12M10 5.5V11.5M15 6V11" />
</>);

export const Molecule = createIcon('molecule', <>
    <circle cx="9.5" cy="14.5" r="4" fill="currentColor" fillOpacity="0.18" stroke="none" />
    <circle cx="9.5" cy="14.5" r="4" />
    <circle cx="17.5" cy="17.5" r="2.5" />
    <circle cx="15.5" cy="5.5" r="2.5" />
    <path d="M13.25 15.9L15.16 16.62M11.72 11.17L14.11 7.58" />
</>);

export const Ring = createIcon('ring', <>
    <circle cx="12" cy="12" r="4" fill="currentColor" fillOpacity="0.18" stroke="none" />
    <path d="M21 12L16.5 19.79L7.5 19.79L3 12L7.5 4.21L16.5 4.21Z" />
    <circle cx="12" cy="12" r="4" />
</>);

export const Orbit = createIcon('orbit', <>
    <circle cx="12" cy="12" r="3.5" fill="currentColor" fillOpacity="0.18" stroke="none" />
    <circle cx="12" cy="12" r="3.5" />
    <ellipse cx="12" cy="12" rx="9" ry="5" transform="rotate(-30 12 12)" />
</>);

export const Helix = createIcon('helix', <>
    <path d="M7 12C7 14 9.5 15 12 16C14.5 15 17 14 17 12Z" fill="currentColor" fillOpacity="0.18" stroke="none" />
    <path d="M7 4C7 8 17 8 17 12C17 16 7 16 7 20M17 4C17 8 7 8 7 12C7 16 17 16 17 20" />
    <path d="M7 12H17" />
</>);

export const Shell = createIcon('shell', <>
    <rect x="8" y="17" width="8" height="3.5" rx="1.5" fill="currentColor" fillOpacity="0.18" stroke="none" />
    <path d="M12 17L3.64 7.71A12.5 12.5 0 0 1 20.36 7.71Z" />
    <path d="M10.21 12.33L7.52 5.33M13.79 12.33L16.48 5.33M12 12L12 4.5" />
    <rect x="8" y="17" width="8" height="3.5" rx="1.5" />
</>);

export const Flask = createIcon('flask', <>
    <path d="M7.5 14.5L5.59 18.33A1.5 1.5 0 0 0 6.93 20.5H17.07A1.5 1.5 0 0 0 18.41 18.33L16.5 14.5Z" fill="currentColor" fillOpacity="0.18" stroke="none" />
    <rect x="9" y="3" width="6" height="3.5" rx="1.5" />
    <path d="M10.5 6.5V8.5L5.59 18.33A1.5 1.5 0 0 0 6.93 20.5H17.07A1.5 1.5 0 0 0 18.41 18.33L13.5 8.5V6.5M7.5 14.5H16.5" />
</>);

export const GelDrop = createIcon('gel-drop', <>
    <path d="M5 19C5 14.5 8 13 10.5 12.5C12.5 12 12.5 7.5 14 7.5C16.5 7.5 19 12.5 19 19Z" fill="currentColor" fillOpacity="0.18" stroke="none" />
    <path d="M3.5 19H20.5M5 19C5 14.5 8 13 10.5 12.5C12.5 12 12.5 7.5 14 7.5C16.5 7.5 19 12.5 19 19" />
</>);

/** Every Cadence icon by its kebab-case name. */
export const cadenceIcons = {
    'today': Today,
    'timeline': Timeline,
    'log': Log,
    'tests': Tests,
    'you': You,
    'injection': Injection,
    'tablet': Tablet,
    'patch': Patch,
    'gel': Gel,
    'sublingual': Sublingual,
    'reminder': Reminder,
    'assistant': Assistant,
    'check': Check,
    'in-target': InTarget,
    'up': Up,
    'down': Down,
    'attention': Attention,
    'info': Info,
    'close': Close,
    'clock': Clock,
    'calendar': Calendar,
    'snooze': Snooze,
    'skip': Skip,
    'repeat': Repeat,
    'supplies': Supplies,
    'reorder': Reorder,
    'site': Site,
    'blood-drop': BloodDrop,
    'chevron-right': ChevronRight,
    'chevron-down': ChevronDown,
    'back': Back,
    'minus': Minus,
    'plus': Plus,
    'more': More,
    'backed-up': BackedUp,
    'sync': Sync,
    'lock': Lock,
    'two-step': TwoStep,
    'key': Key,
    'sign-in': SignIn,
    'sign-out': SignOut,
    'eye': Eye,
    'language': Language,
    'appearance': Appearance,
    'weight': Weight,
    'summary': Summary,
    'export': Export,
    'import': Import,
    'share': Share,
    'link': Link,
    'copy': Copy,
    'external': External,
    'edit': Edit,
    'delete': Delete,
    'server': Server,
    'terminal': Terminal,
    'laptop': Laptop,
    'phone': Phone,
    'activity-log': ActivityLog,
    'permissions': Permissions,
    'moon': Moon,
    'spinner': Spinner,
    'eye-off': EyeOff,
    'cloud': Cloud,
    'cloud-off': CloudOff,
    'cloud-upload': CloudUpload,
    'cloud-download': CloudDownload,
    'search': Search,
    'settings': Settings,
    'sliders': Sliders,
    'users': Users,
    'shield': Shield,
    'shield-off': ShieldOff,
    'passkey': Passkey,
    'image-add': ImageAdd,
    'image-off': ImageOff,
    'template': Template,
    'template-add': TemplateAdd,
    'reset': Reset,
    'save': Save,
    'notice': Notice,
    'database': Database,
    'hard-drive': HardDrive,
    'merge': Merge,
    'desktop': Desktop,
    'devices': Devices,
    'chevron-up': ChevronUp,
    'chevron-left': ChevronLeft,
    'off': Off,
    'verified': Verified,
    'select': Select,
    'forward': Forward,
    'rewind': Rewind,
    'gauge': Gauge,
    'radar': Radar,
    'wind': Wind,
    'molecule': Molecule,
    'ring': Ring,
    'orbit': Orbit,
    'helix': Helix,
    'shell': Shell,
    'flask': Flask,
    'gel-drop': GelDrop,
} as const;

export type CadenceIconName = keyof typeof cadenceIcons;
